### ISSUE TITLE
LK8000 use?

### ISSUE THREAD

**Issue by JBlyth** [piopawlu/pda-injector#1]
I would be very interested to try this with LK8000 instead of XCSoar. What steps would I need to take to accomplish this? I am familiar with Visual Studio and some programming languages.

I believe Condor 3 will have an LXNav 90xx option, but being able to also use XCSoar or LK8000 would indeed be welcome.

Cheers
John in Sunny Carnarvon - Western Australia

**Comment by piopawlu** [comment]
LK8000 is already directly supported. All you need to do is to modify the config file (pda.ini) and set the **window** to LK8000 in the [app] section. Take a look at the main project page for the template pda.ini (https://github.com/piopawlu/pda-injector?tab=readme-ov-file#configuration)

**Comment by JBlyth** [comment]
Thank you, Piopawlu. That is most useful.

One more question:- I already use AutoHotkey to pass Keystrokes to LK8000. Because I have so many combinations set up in my Thrustmaster Warhog Profile, I need to use key combinations such as:-

;Next Waypoint - Menu/Nav/Waypoint Next (**using Alt+S**)
!S::
SendToLK("{F1}")
SendMouse("Nav")
SendMouse("Waypoint`nFinish")
SendMouse("Waypoint`nNext")
SendMouse("Cancel")
Return

Will they continue to work, or do I need to reimplement those multiple keystrokes via the pda.ini file somehow?

**Comment by piopawlu** [comment]
It should all continue to work, and if you are already using the AutoHotkey you don’t need to enable the input passing in pda.ini.

**Comment by JBlyth** [comment]
Wow. That's pretty amazing. Well Done!!!!!!

LK8000 works well. All my AutoHotKey shortcuts work except for my manual mouse control.

I am getting quite a lot of "aliasing" on the LK8000 screen fonts, but I can see great potential here.

It would be nice not to lose access to the Condor PDA screen 3, but I am sure there will be a work around for that. I seldom use screen 2 (I think it is), so I'll look at modifying the option to that. 

Sadly I'm busy for the next 10 days, but I will look into it more after that.

**Comment by piopawlu** [comment]
I’ll add an option to use half the resolution in the next build. The display looks slightly better when the screen is stretched rather than being “squeezed”.. that’s of course at a cost of lower overall resolution.

I generally recenter my VR view while I lean back slightly (10-20cm) and then move back forward to end up closer to the virtual cockpit and the PDA display. That gives me a pretty clear view.
