### ISSUE TITLE
XCSoar screen is smaller than the PDA screen of the glider

### ISSUE THREAD

**Issue by rdevries1965** [piopawlu/pda-injector#3]
When I run version 4 or 5 the XCSoar screren projected on page 3 of the PDA is much smaller compared to the PDA screen. The not used part of the PDA screen is flickering.
![example](https://github.com/piopawlu/pda-injector/assets/49791726/3e8dbceb-0bb5-4816-8430-c5e78c7236c7)

**Comment by piopawlu** [comment]
What version of Condor are you running? Can you share your config file? Does the XCSoar window get auto-resized when starting?

**Comment by rdevries1965** [comment]
Hi,

I am running Condor 2.2.0.
What config file do you need ?
Does the XCSoar window get auto-resized when starting? Yes I think it does. It opens XCSOar.exe with an -portrait command.

I have tested without -portait command in the startup and the issue remains. 


Best regards,

Ronald

________________________________
Van: Piotr ***@***.***>
Verzonden: vrijdag 28 juni 2024 21:38
Aan: piopawlu/pda-injector ***@***.***>
CC: rdevries1965 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [piopawlu/pda-injector] XCSoar screen is smaller than the PDA screen of the glider (Issue #3)


What version of Condor are you running? Can you share your config file? Does the XCSoar window get auto-resized when starting?

**Comment by piopawlu** [comment]
Are you using any other patches or modifications? What glider is it? I haven't seen any with a LXNAV branded textures but I don't own all the extra gliders. I wanted to take a look at the pda.ini file where the injector is configured.

**Comment by rdevries1965** [comment]
I am using the latest Condor version.
Tests initially done with VR and also with VR. Same result.
Used the ASW28 and Cirrus.
The pda.ini from the Condor2 folder contains the following:
[app]
window=XCSoar

# Uncomment if you want to enable input passing to the target app
#pass_input=true

# If enabled, will pass all keys to the target app as long as shift key is held down
#pass_all_with_shift=false

# If pass_input is enabled above, you can enter up to 32 virtualkey codes that you want passed or mapped if you use VK1:VK2
# You can read the list of Virtual Keys at https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
#pass_key_1=0x4E:0x28 ; N -> down
#pass_key_2=0x48:0x25 ; H -> left
#pass_key_3=0x55:0x26 ; U -> up
#pass_key_4=0x4B:0x27 ; K -> right
#pass_key_5=0x4D:0x28 ; M -> down
#pass_key_6=0x4A:0x28 ; J -> enter
#pass_key_7=0x59:0x1B ; Y -> ESC
#pass_key_8=0x4A:0x0D ; J -> ENTER

[pda]
enabled=true
page=2
swap_colours=true
show_waiting_screen=true

**Comment by piopawlu** [comment]
When you run it without the XCSoar (keeping the config as it is) does the "waiting screen" show full size or is it also only taking a part of the PDA? To me it seems that XCSoar window cannot be automatically resized to the correct size (due to arguments passed to it) so it is not big enough to be copied.

**Comment by rdevries1965** [comment]
Hi,

See printscreen, looks like full PDA to me...

Ronald
[cid:14addd83-51b6-420e-8b34-1e056c0f2a15]
________________________________
Van: Piotr ***@***.***>
Verzonden: woensdag 3 juli 2024 18:59
Aan: piopawlu/pda-injector ***@***.***>
CC: rdevries1965 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [piopawlu/pda-injector] XCSoar screen is smaller than the PDA screen of the glider (Issue #3)


When you run it without the XCSoar (keeping the config as it is) does the "waiting screen" show full size or is it also only taking a part of the PDA? To me it seems that XCSoar window cannot be automatically resized to the correct size (due to arguments passed to it) so it is not big enough to be copied.

**Comment by rdevries1965** [comment]
![PDA waiting](https://github.com/piopawlu/pda-injector/assets/49791726/bfb4ab3a-5b79-46b0-a24f-6fd00dd5b38d)

attached file

**Comment by piopawlu** [comment]
Yeah, then it’s down to XCSoar preventing window size change. Try to start XCSoar without any arguments and see if that helps.

**Comment by rdevries1965** [comment]
It did not change but when I resize the XCSOar window on the desktop the PDA follows and I was able to resize to fully use the secreen. Works for me.
![PDA repaired](https://github.com/piopawlu/pda-injector/assets/49791726/2daea05c-2749-4f27-b69f-31d7c229fcc0)

**Comment by piopawlu** [comment]
Given that you’re okay with the solution I’ll close this issue.

**Comment by holmesal** [comment]
FYI - I had a similar issue on a high-resolution display (the rendered XCSoar was only taking up about half of the available PDA space), and I wasn't able to resize the XCSoar window without it snapping back. Unchecking "High DPI Scaling Override" in the Condor shortcut compatibility settings fixed it for me, and as a bonus, my Condor UI is no longer tiny. Described in this thread: https://www.condorsoaring.com/forums/viewtopic.php?t=18297#p158066
