### ISSUE TITLE
Condor 3 support?

### ISSUE THREAD

**Issue by lordfolken** [piopawlu/pda-injector#5]
I think condor 3 uses the same DX11 version as c2. Would it be possible to add support? The c3 included lx seems to use a similar approach.

**Comment by piopawlu** [comment]
I only just downloaded C3 when it was released after 8 hours of failed attempts. I haven’t yet had time to play it other than just test starting it, but yeah I will make an attempt to bring the injection back. I would really like to wait until condor 3.0.1 to avoid spending time on a binary that will be replaced with a first bug fix release :)

**Comment by lordfolken** [comment]
Any luck? Issues?

**Comment by piopawlu** [comment]
Yeah,, I got it running in C3 3.0.0,, now that the patch is released I will try to make a release.. I wanted to do it a week ago but other things were in the way,, hopefully some day this week.

https://www.condorsoaring.com/forums/viewtopic.php?p=188681&sid=2f275f92304224519d29befe993f7122#p188681

**Comment by lordfolken** [comment]
So after some effort, i got it to build in vstudio. Really not my environment. However C3 doesn't  start anymore. :)

**Comment by lordfolken** [comment]
So at first i couldn't get the prerlease downloaded from github working. 
(Renaming the dll, copying in the new one, adding pda.ini) 

Then XCSoar wouldn't show up. 

I downloaded and built your code but changed the output path in the visualstudio project to d:/condor3 (not c:/condor3) as it was. 
This then worked and xcsoar shows up in c3 !

Could there be a hardcoded path issue?

**Comment by piopawlu** [comment]
Hmm, I don't think it's path related.. there's no usage of filesystem at all in the code. It could be simply that the build I uploaded is faulty.. I was running debug build and made a release for the zip package which I didn't test.. I will take a look in the evening when I have some time.

I'm glad you could build and get it running yourself at least :-)

**Comment by piopawlu** [comment]
Right,, so the binary release had a C2 build dll included,, it's solved now and I will mark it as resolved.

**Comment by doramail** [comment]
> Right,, so the binary release had a C2 build dll included,, it's solved now and I will mark it as resolved.

It works flawlessly, many thanks !
